# Deploy news to Production
# Triggers on push to main branch

name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    env:
      DEPLOY_DIR: /var/www/news

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure git for commits
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Install dependencies
        run: npm install

      - name: Commit lockfile changes
        continue-on-error: true
        run: |
          git add package-lock.json
          git diff-index --quiet HEAD || git commit -m "Update package-lock.json"

      - name: Check package.json scripts
        run: |
          echo "=== Available npm scripts ==="
          npm run

      - name: Create .env file
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "AUTH_TRUST_HOST=true" >> .env
          echo "NEXT_PUBLIC_NEWS_API_KEY=${{ secrets.NEXT_PUBLIC_NEWS_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_YOUTUBE_API_KEY=${{ secrets.NEXT_PUBLIC_YOUTUBE_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_MEDIASTACK_API_KEY=${{ secrets.NEXT_PUBLIC_MEDIASTACK_API_KEY }}" >> .env
          echo "=== Created .env file ==="
          cat .env

      - name: Run build with error handling
        run: |
          echo "=== Starting build process ==="
          npm run build || {
            echo "=== Build failed, checking for alternatives ==="
            if npm run | grep -q "build"; then
              echo "Build script exists but failed"
            else
              echo "No build script found, trying alternatives"
              npm run dev:build || npm run compile || npm run make
            fi
            echo "=== Listing all files to see what was generated ==="
            find . -name "*.js" -o -name "*.html" -o -name "*.json" | head -20
          }

      - name: List all files and directories
        run: |
          echo "=== Complete directory structure ==="
          find . -type f -name "*.js" -o -name "*.ts" -o -name "*.tsx" -o -name "*.jsx" -o -name "*.html" -o -name "*.json" -o -name "*.css" | sort

      - name: Upload any generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            **/*
            !.git
            !node_modules
          if-no-files-found: warn
