# Deploy news to Production
# Triggers on push to main branch

name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    env:
      DEPLOY_DIR: /var/www/news

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure git for commits
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Install dependencies
        run: npm install

      - name: Commit lockfile changes
        continue-on-error: true
        run: |
          git add package-lock.json
          git diff-index --quiet HEAD || git commit -m "Update package-lock.json"

      - name: Create .env file
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "AUTH_TRUST_HOST=true" >> .env
          echo "NEXT_PUBLIC_NEWS_API_KEY=${{ secrets.NEXT_PUBLIC_NEWS_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_YOUTUBE_API_KEY=${{ secrets.NEXT_PUBLIC_YOUTUBE_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_MEDIASTACK_API_KEY=${{ secrets.NEXT_PUBLIC_MEDIASTACK_API_KEY }}" >> .env

      - name: Run build
        run: npm run build

      - name: List files after build
        run: |
          echo "=== Current directory contents ==="
          ls -la
          echo "=== .next directory contents (if exists) ==="
          ls -la .next/ 2>/dev/null || echo ".next directory does not exist"
          echo "=== Checking other possible build directories ==="
          ls -la build/ 2>/dev/null || echo "build directory does not exist"
          ls -la dist/ 2>/dev/null || echo "dist directory does not exist"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next/
            build/
            dist/
            public/
            .env
